/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Code File\\MinisCloudOS\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-dbb55052",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dbb55052").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-44f2d05b",
    path: "/des/REAMME.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44f2d05b").then(next)
    },
  },
  {
    name: "v-c872bef8",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c872bef8").then(next)
    },
  },
  {
    name: "v-7f0d7cf0",
    path: "/des/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f0d7cf0").then(next)
    },
  },
  {
    path: "/des/index.html",
    redirect: "/des/"
  },
  {
    name: "v-2c541c24",
    path: "/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c541c24").then(next)
    },
  },
  {
    name: "v-66e73f77",
    path: "/des/other.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66e73f77").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]