/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Code File\\MinisCloudOS\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-c872bef8",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c872bef8").then(next)
    },
  },
  {
    name: "v-1de84374",
    path: "/guide_CN.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1de84374").then(next)
    },
  },
  {
    name: "v-293aec8c",
    path: "/list/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-293aec8c").then(next)
    },
  },
  {
    path: "/list/index.html",
    redirect: "/list/"
  },
  {
    name: "v-2c541c24",
    path: "/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c541c24").then(next)
    },
  },
  {
    name: "v-23097d78",
    path: "/guide_EN.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23097d78").then(next)
    },
  },
  {
    name: "v-96954eb8",
    path: "/enable_assistance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96954eb8").then(next)
    },
  },
  {
    name: "v-dbb55052",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dbb55052").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6d608651",
    path: "/list/other1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d608651").then(next)
    },
  },
  {
    name: "v-7bae5471",
    path: "/list/other2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7bae5471").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]