/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/index.png",
        "heroText": "Hero MinisCloud",
        "tagline": "Hero This is for OS",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-dbb55052",
      "path": "/"
    },
    {
      "title": "des总支",
      "frontmatter": {
        "title": "des总支"
      },
      "regularPath": "/list/",
      "relativePath": "list/README.md",
      "key": "v-293aec8c",
      "path": "/list/",
      "headers": [
        {
          "level": 2,
          "title": "拜火教总纲",
          "slug": "拜火教总纲"
        }
      ]
    },
    {
      "title": "联系我们的具体方式",
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-2c541c24",
      "path": "/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "联系我们的具体方式",
          "slug": "联系我们的具体方式"
        }
      ]
    },
    {
      "title": "侧边栏大纲标题",
      "frontmatter": {
        "title": "侧边栏大纲标题"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-c872bef8",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "直接路由展示",
          "slug": "直接路由展示"
        },
        {
          "level": 2,
          "title": "终端调起情况",
          "slug": "终端调起情况"
        },
        {
          "level": 3,
          "title": "第一步",
          "slug": "第一步"
        },
        {
          "level": 3,
          "title": "第二步",
          "slug": "第二步"
        },
        {
          "level": 3,
          "title": "第三步",
          "slug": "第三步"
        },
        {
          "level": 2,
          "title": "实际工作内容",
          "slug": "实际工作内容"
        },
        {
          "level": 2,
          "title": "微软合作",
          "slug": "微软合作"
        },
        {
          "level": 2,
          "title": "Mini主机涵盖",
          "slug": "mini主机涵盖"
        },
        {
          "level": 2,
          "title": "联系我们",
          "slug": "联系我们"
        }
      ]
    },
    {
      "title": "细节描述",
      "frontmatter": {
        "title": "细节描述"
      },
      "regularPath": "/list/other1.html",
      "relativePath": "list/other1.md",
      "key": "v-6d608651",
      "path": "/list/other1.html",
      "headers": [
        {
          "level": 2,
          "title": "直接路由展示",
          "slug": "直接路由展示"
        }
      ]
    },
    {
      "title": "详细解释",
      "frontmatter": {
        "title": "详细解释"
      },
      "regularPath": "/list/other2.html",
      "relativePath": "list/other2.md",
      "key": "v-7bae5471",
      "path": "/list/other2.html",
      "headers": [
        {
          "level": 2,
          "title": "终端调起情况",
          "slug": "终端调起情况"
        },
        {
          "level": 3,
          "title": "第一步",
          "slug": "第一步"
        },
        {
          "level": 3,
          "title": "第二步",
          "slug": "第二步"
        },
        {
          "level": 3,
          "title": "第三步",
          "slug": "第三步"
        }
      ]
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "sidebar": [
      "",
      "about",
      "contact",
      {
        "title": "组合模块",
        "path": "/list/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/list/other1",
          "/list/other2"
        ]
      }
    ],
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "Contact",
        "ariaLabel": "contact Menu",
        "items": [
          {
            "text": "Email",
            "link": "/contact/"
          },
          {
            "text": "Phone",
            "link": "/contact/"
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}