/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/MinisCloudOS/",
  "headTags": [],
  "pages": [
    {
      "title": "如何开启远程协助？",
      "frontmatter": {
        "title": "如何开启远程协助？"
      },
      "regularPath": "/enable_assistance.html",
      "relativePath": "enable_assistance.md",
      "key": "v-96954eb8",
      "path": "/enable_assistance.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "1. 登录管理员账号，点击“设置”模块",
          "slug": "_1-登录管理员账号-点击-设置-模块"
        },
        {
          "level": 2,
          "title": "2. 点击“管理员设置”，找到SN码",
          "slug": "_2-点击-管理员设置-找到sn码"
        },
        {
          "level": 2,
          "title": "3. 点击“SN”，获得SN码，点击复制",
          "slug": "_3-点击-sn-获得sn码-点击复制"
        },
        {
          "level": 2,
          "title": "4. 回到登录起始页，点击产品展示头图",
          "slug": "_4-回到登录起始页-点击产品展示头图"
        },
        {
          "level": 2,
          "title": "5. 点击“开启远程协助”",
          "slug": "_5-点击-开启远程协助"
        },
        {
          "level": 2,
          "title": "6. 输入复制的SN码",
          "slug": "_6-输入复制的sn码"
        },
        {
          "level": 2,
          "title": "7. 开启成功，获得远程协助码，点击复制",
          "slug": "_7-开启成功-获得远程协助码-点击复制"
        },
        {
          "level": 2,
          "title": "8. 将远程协助码提供给工作人员联系技术人员对接即可",
          "slug": "_8-将远程协助码提供给工作人员联系技术人员对接即可"
        }
      ]
    },
    {
      "title": "des总支",
      "frontmatter": {
        "title": "des总支"
      },
      "regularPath": "/list/",
      "relativePath": "list/README.md",
      "key": "v-293aec8c",
      "path": "/list/",
      "headers": [
        {
          "level": 2,
          "title": "拜火教总纲",
          "slug": "拜火教总纲"
        }
      ]
    },
    {
      "title": "侧边栏大纲标题",
      "frontmatter": {
        "title": "侧边栏大纲标题"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-c872bef8",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "直接路由展示",
          "slug": "直接路由展示"
        },
        {
          "level": 2,
          "title": "终端调起情况",
          "slug": "终端调起情况"
        },
        {
          "level": 3,
          "title": "第一步",
          "slug": "第一步"
        },
        {
          "level": 3,
          "title": "第二步",
          "slug": "第二步"
        },
        {
          "level": 3,
          "title": "第三步",
          "slug": "第三步"
        },
        {
          "level": 2,
          "title": "实际工作内容",
          "slug": "实际工作内容"
        },
        {
          "level": 2,
          "title": "微软合作",
          "slug": "微软合作"
        },
        {
          "level": 2,
          "title": "Mini主机涵盖",
          "slug": "mini主机涵盖"
        },
        {
          "level": 2,
          "title": "联系我们",
          "slug": "联系我们"
        }
      ]
    },
    {
      "title": "细节描述",
      "frontmatter": {
        "title": "细节描述"
      },
      "regularPath": "/list/other1.html",
      "relativePath": "list/other1.md",
      "key": "v-6d608651",
      "path": "/list/other1.html",
      "headers": [
        {
          "level": 2,
          "title": "直接路由展示",
          "slug": "直接路由展示"
        }
      ]
    },
    {
      "title": "详细解释",
      "frontmatter": {
        "title": "详细解释"
      },
      "regularPath": "/list/other2.html",
      "relativePath": "list/other2.md",
      "key": "v-7bae5471",
      "path": "/list/other2.html",
      "headers": [
        {
          "level": 2,
          "title": "终端调起情况",
          "slug": "终端调起情况"
        },
        {
          "level": 3,
          "title": "第一步",
          "slug": "第一步"
        },
        {
          "level": 3,
          "title": "第二步",
          "slug": "第二步"
        },
        {
          "level": 3,
          "title": "第三步",
          "slug": "第三步"
        }
      ]
    },
    {
      "title": "联系我们的具体方式",
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-2c541c24",
      "path": "/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "联系我们的具体方式",
          "slug": "联系我们的具体方式"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/index.png",
        "heroText": "N5 && N5 pro",
        "tagline": "User Manual for MinisCloudOS",
        "actionText": "Let' go →",
        "actionLink": "/enable_assistance/",
        "features": null,
        "footer": "Copyright © 2025 Minisforum. All rights reserved"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-dbb55052",
      "path": "/"
    }
  ],
  "themeConfig": {
    "searchMaxSuggestions": 10,
    "sidebar": {
      "/": [
        "",
        "about",
        "contact",
        "enable_assistance",
        "/list/"
      ],
      "/list/": [
        "/list/other1",
        "/list/other2"
      ]
    },
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "Contact",
        "ariaLabel": "contact Menu",
        "items": [
          {
            "text": "Email",
            "link": "/contact/"
          },
          {
            "text": "Phone",
            "link": "/contact/"
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}